# Docker settings
[docker]
host = "tcp://127.0.0.1:2375"
local-ip = "127.0.0.1"
port-range = "25580:25590"
server_check_interval = 60 # In seconds
prune-containers = false # Prune containers on startup

[velocity]
auto-add-servers = true # Add servers to velocity /server command

# Scaling server settings
[[server]]
prefix-name = "lobby"
docker-image = "lobby-image"
docker-tag = "latest"
min-concurrent-servers = 1
max-concurrent-servers = 5
max-players = 10 # The max players that can be in the server
downscale-if-empty = true # Downscale the server if it's empty

[[server]]
prefix-name = "uhc"
image = "uhc-image"
tag = "latest"
min-concurrent-servers = 1
max-concurrent-servers = 3
max-players = 100 # The max players that can be in the server
downscale-if-empty = false # Downscale the server if it's empty
